profile: full
#profile: light
ceip_policy_disclosed: true 
buildservice:
  kp_default_repository: "harbor.apps.cf.tanzutime.com/dekt-system/build-service"
  kp_default_repository_username: "dektlong"
  kp_default_repository_password: "appCl0udlong"
  tanzunet_username: "dekel@vmware.com"
  tanzunet_password: "appCl0ud#"
  descriptor_name: "tap-1.0.0-full"
  enable_automatic_dependency_updates: true
supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "harbor.apps.cf.tanzutime.com"
    repository: "dekt-apps"
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: "dekt.io"
  
cnrs:
  #domain_template: "{{.Name}}.{{.Domain}}"
  domain_name: "dekt.io"

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  server:
    service_type: "ClusterIP"
    
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "dekt.io"
  app_config:
    app:
      baseUrl: "http://tap-gui.dekt.io"
    catalog:
      locations:
        - type: url
          target: https://github.com/dektlong/tap-demo-share/blob/main/backstage/default/catalog-info.yaml
        - type: url
          target: https://github.com/dektlong/tap-demo-share/blob/main/backstage/yelb/catalog-info.yaml
    backend:
      baseUrl: "http://tap-gui.dekt.io"
      cors:
        origin: "http://tap-gui.dekt.io"

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  namespace: # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"