profile: full
#profile: light
ceip_policy_disclosed: true 
buildservice:
  kp_default_repository: #e.g "harbor.apps.cf.tanzutime.com/dekt-system/build-service"
  kp_default_repository_username: 
  kp_default_repository_password: 
  tanzunet_username: 
  tanzunet_password: 
  descriptor_name: "tap-1.0.0-full"
  enable_automatic_dependency_updates: true
supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: #e.g. "harbor.apps.cf.tanzutime.com"
    repository: #e.g. "dekt-apps"
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: #e.g. "dekt.io"
  
cnrs:
  #domain_template: "{{.Name}}.{{.Domain}}"
  domain_name: #e.g. "dekt.io"

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  server:
    service_type: "ClusterIP"
    
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: #e.g. "dekt.io"
  app_config:
    app:
      baseUrl: #e.g. "http://tap-gui.dekt.io"
    catalog:
      locations:
        - type: url
          target: https://github.com/dektlong/_DevXDemo/blob/main/config-templates/backstage/default/catalog-info.yaml
        - type: url
          target: https://github.com/dektlong/_DevXDemo/blob/main/config-templates/backstage/yelb/catalog-info.yaml
        - type: url
          target: https://github.com/dektlong/_DevXDemo/blob/main/config-templates/backstage/dekt/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.sys.dekt.io
      cors:
        origin: http://tap-gui.sys.dekt.io

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  namespace: "dekt-apps" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"